---

- hosts: all
  become: true
  tasks:

  - name: apt update repository index
    apt:
      update_cache: true

  - name: Uninstall apache2 package
    apt:
      name: apache2
      state: absent
