---

- hosts: master
  become: true
  tasks:

  - name: Install apache and nano package
    package:
      name:
         - "{{ apache_package }}"
      state: latest
      update_cache: true

- hosts: worker
  become: true
  tasks:

  - name: Install apache and nano package
    package:
      name:
         - "{{ nano_package }}"
      state: latest
      update_cache: true
