---

- hosts: all
  become: true
  tasks:

  - name: apt update repository index
    apt:
      update_cache: true
    when: ansible_distribution in ['Debian'] and ansible_distribution_version == "12"

  - name: Install apache2 package
    apt:
      name: apache2
      state: latest
